services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~ZTfM0nyB"
      - key: DATABASE_URL
        fromDatabase:"dpg-d2s14lur433s738eo720-a"
          name: my-database
          property: connectionString
